# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FastFeet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FastFeet
  pod 'Alamofire'

  target 'FastFeetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FastFeetUITests' do
    # Pods for testing
  end

end
